services:

  backend:
    build: ./apps
    restart: always
    ports:
      - "3000"
    environment:
      - DB_NAME=training
      - DB_HOST=172.23.14.106
      - DB_USER=peserta
      - DB_PASS=password
      - APP_PORT=3000
    volumes:
      - app-data:/app/public/images

  phpmyadmin:
    image: "phpmyadmin"
    restart: always
    ports:
      - "9080:80"
    environment:
      - PMA_HOST=db

  web:
    build: ./nginx
    restart: always
    ports:
    - "80:80"
    depends_on:
    - backend

volumes:
  app-data: